name: deploy

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.3'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Create .env
        run: cp .env.example .env

      - name: Update Composer
        run: composer self-update

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Delete composer.lock
        run: rm -f composer.lock

      - name: Install composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist

      - name: Set Application Encryption Key
        run: php artisan key:generate --ansi

      - name: Create Storage Link
        run: php artisan storage:link

      - name: Run migrations
        run: php artisan migrate --force

      - name: Install node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Deploy to server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd htdocs/ecommerce.horsenco.com
            git fetch --all
            git checkout main
            git pull origin main
            composer install --no-interaction --no-dev --prefer-dist
            npm ci
            npm run build
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            chmod -R 775 storage bootstrap/cache public/uploads
